version: 2
jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run:
          name: Install debian-packaged dependencies
          command: |
            apt update
            apt install -y ldc git make curl gcc
            ln -s /usr/bin/ldc2 /usr/bin/ldc
      - run:
          name: Install crystal
          command: |
            CRYSTAL_VERSION=0.24.2
            CRYSTAL_BIN=$pwd/crystal-$VERSION/bin/crystal
            curl -L -o c.tar.gz https://github.com/crystal-lang/crystal/releases/download/0.24.2/crystal-$VERSION-1-linux-x86_64.tar.gz
            tar -xvzf c.tar.gz
            chmod +x $CRYSTAL_BIN
            ln -s $CRYSTAL_BIN /usr/bin/crystal
      - run:
          name: Install bsdscheme
          command: |
            make
            make install
      - run:
          name: Install btest
          command: |
            git clone https://github.com/briansteffens/btest
            cd btest
            make
            make install
      - run:
          name: Run bsdscheme tests
          command: btest
