version: 2
jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run:
          name: Install debian-packaged dependencies
          command: |
            apt update
            apt install -y curl git ldc file build-essential libyaml-dev libpcre++-dev libevent-dev
            ln -s /usr/bin/ldc2 /usr/bin/ldc
      - run:
          name: Install btest
          command: |
            VERSION=0.24.2
            CRYSTAL_BIN=/tmp/crystal-$VERSION/bin/crystal
            cd /tmp
            curl -L -o c.tar.gz https://github.com/crystal-lang/crystal/releases/download/$VERSION/crystal-$VERSION-1-linux-x86_64.tar.gz
            tar xzf c.tar.gz
            chmod +x $CRYSTAL_BIN
            ln -s $CRYSTAL_BIN /usr/bin/crystal
            git clone https://github.com/briansteffens/btest
            cd btest
            make
            make install
      - run:
          name: Install bsdscheme
          command: |
            make
            make install
      - run:
          name: Run bsdscheme tests
          command: btest
