version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install debian-packaged dependencies
          command: sudo apt-get install -y ldc crystal git
      - run:
          name: Install bsdscheme
          command: |
            make
            sudo make install
      - run:
          name: Install btest
          command: |
            git clone https://github.com/briansteffens/btest
            cd btest
            make
            sudo make install
      - run: Run bsdscheme tests
          command: btest
